<<<<<<< HEAD
# Generated by Django 2.2.1 on 2019-05-19 19:28
=======
# Generated by Django 2.2.1 on 2019-05-19 19:29
>>>>>>> a3a62d40c4d40fccd4ab99b146303dd68785e395

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='contas_image/')),
                ('conta_bancaria', models.IntegerField(null=True)),
                ('numero_agencia', models.IntegerField(null=True)),
                ('nome_titular', models.CharField(max_length=100, null=True)),
<<<<<<< HEAD
                ('codigo_banco', models.IntegerField(null=True)),
=======
                ('codigo_banco', models.IntegerField(max_length=5, null=True)),
>>>>>>> a3a62d40c4d40fccd4ab99b146303dd68785e395
                ('cpf', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Contas Bancária',
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voluntario', models.CharField(max_length=100)),
                ('local', models.TextField()),
                ('dias', models.CharField(blank=True, max_length=50, null=True)),
                ('horario', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(upload_to='doacao_image/')),
            ],
            options={
                'verbose_name': 'Ponto de arrecadação',
                'verbose_name_plural': 'Pontos de arrecadação',
            },
        ),
    ]
