# Generated by Django 2.2.1 on 2019-06-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Apoia-se',
            },
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='contas_image/')),
                ('conta_bancaria', models.IntegerField(null=True)),
                ('numero_agencia', models.IntegerField(null=True)),
                ('nome_titular', models.CharField(max_length=100, null=True)),
                ('codigo_banco', models.IntegerField(null=True)),
                ('cpf', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Contas Bancária',
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voluntario', models.CharField(max_length=100)),
                ('local', models.TextField()),
                ('dias', models.CharField(blank=True, max_length=50, null=True)),
                ('horario', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(upload_to='doacao_image/')),
            ],
            options={
                'verbose_name': 'Ponto de arrecadação',
                'verbose_name_plural': 'Pontos de arrecadação',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=100, null=True)),
                ('Foto', models.ImageField(upload_to='evento_image/')),
                ('Postagem', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Picpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
