# Generated by Django 2.2.1 on 2019-06-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='endereco',
            field=models.CharField(default='Endereço', max_length=350),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='local',
            field=models.CharField(max_length=250),
        ),
    ]
