# Generated by Django 2.2.1 on 2019-05-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_apoia_picpay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apoia',
            options={'verbose_name_plural': 'Apoia-se'},
        ),
    ]
