# Generated by Django 2.2.1 on 2019-05-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_eventos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='dias',
            new_name='dia',
        ),
    ]
