# Generated by Django 2.2.1 on 2019-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20190603_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='info',
            field=models.TextField(default='Digite suas informaçoes aqui'),
        ),
    ]
