# Generated by Django 2.2.1 on 2019-05-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20190519_1653'),
        ('home_page', '0004_auto_20190519_1646'),
    ]

    operations = [
    ]
