# Generated by Django 2.2.1 on 2019-06-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_auto_20190603_1703'),
        ('home_page', '0002_auto_20190604_1109'),
    ]

    operations = [
    ]
